##===- tools/opt/Makefile ----------------------------------*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

LEVEL := ../..
TOOLNAME := softboundcets
LINK_COMPONENTS := bitreader bitwriter asmparser irreader instrumentation scalaropts ipo softboundcets

include $(LEVEL)/Makefile.common
